namespace IslaNova.Core.Domain.Entities.AI
{
    /// <summary>
    /// Stores the vectorized representation of a Property for semantic search (RAG).
    /// Lives in the same PostgreSQL (Supabase) database as the relational data.
    /// </summary>
    public class PropertyEmbedding
    {
        public int Id { get; set; }

        /// <summary>Foreign key to the Property (relational DB side).</summary>
        public int PropertyId { get; set; }

        /// <summary>Plain text built from property fields, used to generate the embedding.</summary>
        public required string PlainText { get; set; }

        /// <summary>
        /// 1536-dimension vector generated by OpenAI text-embedding-3-small.
        /// Stored as float[] in domain; EF Core configuration maps it to pgvector column.
        /// </summary>
        public float[]? Embedding { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}
