<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.16" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IslaNova.Core.Application\IslaNova.Core.Application.csproj" />
    <ProjectReference Include="..\IslaNova.Core.Domain\IslaNova.Core.Domain.csproj" />
  </ItemGroup>

</Project>
